apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: status-reporter
rules:
  - apiGroups:
      - ocs.openshift.io
    resources:
      - storageclients
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - update
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - get
      - list
      - watch
